export const productsData = [
  {
    id: 'dell-laptop-battery-65wh',
    name: 'Dell Laptop Battery 65Wh',
    category: 'Batteries',
    price: 9500,
    image: '/images/main3.webp',
    images: ['/images/main3.webp', '/images/main3.webp', '/images/main3.webp'],
    description: 'Reliable 65Wh battery compatible with Dell laptops for long-lasting performance.',
    rating: 4.5,
  },
  {
    id: 'hp-adapter-45w-type-c',
    name: 'HP Adapter 45W Type-C',
    category: 'Chargers',
    price: 7500,
    image: '/images/main3.webp',
    images: ['/images/main3.webp', '/images/main3.webp', '/images/main3.webp'],
    description: 'Compact 45W Type-C adapter suitable for HP laptops with fast charging support.',
    rating: 4.3,
  },
  {
    id: 'lenovo-battery-48wh',
    name: 'Lenovo Battery 48Wh',
    category: 'Batteries',
    price: 8700,
    image: '/images/main3.webp',
    images: ['/images/main3.webp', '/images/main3.webp', '/images/main3.webp'],
    description: 'Original 48Wh Lenovo battery providing stable backup and performance.',
    rating: 4.2,
  },
  {
    id: 'cooling-pad-pro-rgb',
    name: 'Cooling Pad Pro RGB',
    category: 'Accessories',
    price: 4500,
    image: '/images/main3.webp',
    images: ['/images/main3.webp', '/images/main3.webp', '/images/main3.webp'],
    description: 'RGB cooling pad with dual fans to keep your laptop cool during heavy use.',
    rating: 4.7,
  },
  {
    id: 'usb-c-multiport-hub',
    name: 'USB-C Multiport Hub',
    category: 'Accessories',
    price: 5600,
    image: '/images/main3.webp',
    images: ['/images/main3.webp', '/images/main3.webp', '/images/main3.webp'],
    description: 'Expand your laptop’s connectivity with this high-speed USB-C multiport hub.',
    rating: 4.6,
  },
  {
    id: 'acer-charger-65w',
    name: 'Acer Charger 65W',
    category: 'Chargers',
    price: 6800,
    image: '/images/main3.webp',
    images: ['/images/main3.webp', '/images/main3.webp', '/images/main3.webp'],
    description: '65W Acer original charger for stable power delivery and battery health.',
    rating: 4.4,
  },
  {
    id: 'asus-laptop-battery-56wh',
    name: 'Asus Laptop Battery 56Wh',
    category: 'Batteries',
    price: 8800,
    image: '/images/main3.webp',
    images: ['/images/main3.webp', '/images/main3.webp', '/images/main3.webp'],
    description: 'High-capacity Asus 56Wh battery for extended runtime and durability.',
    rating: 4.5,
  },
  {
    id: 'macbook-pro-charger-60w-magsafe',
    name: 'MacBook Pro Charger 60W Magsafe',
    category: 'Chargers',
    price: 11000,
    image: '/images/main3.webp',
    images: ['/images/main3.webp', '/images/main3.webp', '/images/main3.webp'],
    description: 'Genuine Apple MagSafe 60W charger with magnetic connector for MacBook Pro.',
    rating: 4.8,
  },
  {
    id: 'laptop-stand-adjustable-aluminum',
    name: 'Laptop Stand Adjustable Aluminum',
    category: 'Accessories',
    price: 3900,
    image: '/images/main3.webp',
    images: ['/images/main3.webp', '/images/main3.webp', '/images/main3.webp'],
    description: 'Ergonomic and foldable aluminum laptop stand with height adjustability.',
    rating: 4.4,
  },
  {
    id: 'hp-battery-41wh',
    name: 'HP Battery 41Wh',
    category: 'Batteries',
    price: 7600,
    image: '/images/main3.webp',
    images: ['/images/main3.webp', '/images/main3.webp', '/images/main3.webp'],
    description: 'Durable 41Wh battery built for HP laptops for extended performance.',
    rating: 4.1,
  },
];
